# Generated by Django 4.1.4 on 2023-01-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relations',
            old_name='label',
            new_name='labels',
        ),
    ]
